# Generated by Django 5.0.1 on 2024-01-31 14:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='note',
            name='mod_time',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='notes', to='posts.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='Укажите не более 255 символов', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['mod_time'], name='mod_at_index'),
        ),
    ]
