# Generated by Django 5.0.1 on 2024-02-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_note_content_alter_note_mod_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['mod_time']},
        ),
    ]
